#!/usr/env/php
<?php
/**
 * only run a controller.
 */

use Inhere\Console\Examples\Controller\HomeController;
use Inhere\Console\IO\Input;
use Inhere\Console\IO\Output;
use Toolkit\Cli\Color;

define('BASE_PATH', dirname(__DIR__));

require dirname(__DIR__) . '/test/boot.php';

$input = new Input();
$ctrl  = new HomeController($input, new Output());
$ctrl->setDetached();

try {
    exit($ctrl->run($input->getCommand()));
} catch (\Exception $e) {
    $message = Color::apply('error', $e->getMessage());

    echo \sprintf("%s\nFile %s:%d\nTrace:\n%s\n",
        $message, $e->getFile(), $e->getLine(), $e->getTraceAsString()
    );
}

// can also: see './alone-app' file
