#!/usr/bin/env php
<?php

define('BASE_PATH', dirname(__DIR__));

require dirname(__DIR__) . '/tests/boot.php';

// create app instance
$app = new \Inhere\Console\Application([
    'debug' => true,
    'rootPath' => dirname(__DIR__),
]);

$app->setLogoText('
  _  _    ___  _  _
 | || |  / _ \| || |
 | || |_| | | | || |_
 |__   _| | | |__   _|
    | | | |_| |  | |
    |_|  \___/   |_|
    ');

// require dirname(__DIR__) . '/boot/cli-services.php';

require __DIR__ . '/routes.php';

// run
$app->run();
