#!/usr/env/php
<?php

use Inhere\Console\Examples\HomeController;

define('PROJECT_PATH', dirname(__DIR__));

require __DIR__ . '/s-autoload.php';

$app = new \Inhere\Console\Application([
    'debug' => true,
    'rootPath' => PROJECT_PATH,
]);

$app->controller('home', HomeController::class);

exit(
    (int)$app->runAction('home', $app->getInput()->getCommand(), false, true)
);
