#!/usr/bin/env php
<?php

define('BASE_PATH', dirname(__DIR__));

require dirname(__DIR__) . '/test/boot.php';

// create app instance
$app = new \Inhere\Console\LiteApp;

// register commands
$app->addCommand('test', function () {
    echo "hello\n";
}, 'the description text for the command: test');

$app->addCommand('test1', function () {
    echo "hello\n";
}, 'the description text for the command: test1');

// run
$app->run();
